import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { ROOT, resolveProjectDir } from './shared/dirs.js';

const PROJECTS_DIR = path.join(ROOT, 'projects');
const PROJECTS_FILE = path.join(ROOT, 'projects.json');

function usage() {
  console.log(`Usage:
  node tools/scripts/rough-cut.js --project-id <id> --name <name> --script <path> [options]

Creates or prepares a project, splits the script into shots, promotes them to timeline,
builds prompt packages, and stops before image generation / TTS / MP4 export.

Options:
  --description <text>       Project description for new project
  --project-dir <dir>        Use an explicit project directory instead of --project-id
  --template-project <id>    Copy scenes/characters/props/styles from an existing project
  --force                    Allow replacing existing shots/prompts/timeline generated by this pipeline
  --dry-run                  Print the plan without writing or running child scripts
  --skip-split               Keep existing shots_draft/
  --skip-promote             Keep existing shots/ and timeline
  --max-duration <sec>       Split long shots above this duration (default: 12)
`);
}

function argValue(args, name, fallback = null) {
  const idx = args.indexOf(name);
  return idx >= 0 && idx + 1 < args.length ? args[idx + 1] : fallback;
}

function hasArg(args, name) {
  return args.includes(name);
}

function readJson(filePath, fallback = null) {
  try {
    if (!fs.existsSync(filePath)) return fallback;
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return fallback;
  }
}

function writeJson(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2) + '\n', 'utf-8');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function safeProjectId(id) {
  return /^[A-Za-z0-9_-]+$/.test(String(id || ''));
}

function copyDirIfExists(src, dest, { force = false } = {}) {
  if (!fs.existsSync(src)) return false;
  if (fs.existsSync(dest) && fs.readdirSync(dest).length > 0 && !force) return false;
  fs.mkdirSync(dest, { recursive: true });
  fs.cpSync(src, dest, { recursive: true, force: true });
  return true;
}

function resolveScriptPath(scriptArg, projectDir) {
  if (path.isAbsolute(scriptArg)) return scriptArg;
  const candidates = [
    path.join(projectDir, scriptArg),
    path.resolve(process.cwd(), scriptArg),
    path.join(ROOT, scriptArg)
  ];
  return candidates.find(candidate => fs.existsSync(candidate)) || candidates[0];
}

function stageScript(scriptPath, projectDir) {
  const projectDocs = path.join(projectDir, 'docs');
  ensureDir(projectDocs);
  const stagedPath = path.join(projectDocs, 'script.txt');
  const resolved = path.resolve(scriptPath);
  if (resolved !== path.resolve(stagedPath)) {
    fs.copyFileSync(resolved, stagedPath);
  }
  return stagedPath;
}

function listJsonRel(projectDir, dir) {
  const abs = path.join(projectDir, dir);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs)
    .filter(file => file.endsWith('.json'))
    .sort()
    .map(file => `${dir}/${file}`);
}

function createOrLoadProject({ projectId, projectDirArg, name, description, templateProject, force, dryRun }) {
  if (projectDirArg) {
    const projectDir = path.resolve(process.cwd(), projectDirArg);
    if (!fs.existsSync(path.join(projectDir, 'project.json'))) {
      throw new Error(`project.json not found in --project-dir: ${projectDir}`);
    }
    return { projectDir, projectId: readJson(path.join(projectDir, 'project.json'), {})?.id || path.basename(projectDir), created: false };
  }

  if (!safeProjectId(projectId)) {
    throw new Error('--project-id is required and may only contain letters, numbers, underscores, and hyphens.');
  }

  const projectDir = path.join(PROJECTS_DIR, projectId);
  const projectJson = path.join(projectDir, 'project.json');
  const exists = fs.existsSync(projectJson);
  if (exists) return { projectDir, projectId, created: false };

  if (!name) throw new Error('--name is required when creating a new project.');
  if (dryRun) return { projectDir, projectId, created: true };

  ensureDir(projectDir);
  for (const dir of ['docs', 'shots', 'shots_draft', 'scenes', 'characters', 'props', 'styles', 'assets/audio', 'assets/renders', 'prompts/image', 'reports', 'exports']) {
    ensureDir(path.join(projectDir, dir));
  }

  if (templateProject) {
    const templateDir = resolveProjectDir(templateProject);
    if (!templateDir) throw new Error(`template project not found: ${templateProject}`);
    for (const dir of ['scenes', 'characters', 'props', 'styles']) {
      copyDirIfExists(path.join(templateDir, dir), path.join(projectDir, dir), { force });
    }
  }

  const project = {
    id: projectId,
    name,
    description: description || '',
    default_style_ref: listJsonRel(projectDir, 'styles')[0] || 'styles/cinematic_v1.json',
    defaults: {
      language: 'zh',
      fps: 24,
      aspect: '16:9'
    },
    inventory: {
      scenes: listJsonRel(projectDir, 'scenes'),
      characters: listJsonRel(projectDir, 'characters'),
      props: listJsonRel(projectDir, 'props')
    },
    timeline: []
  };
  writeJson(projectJson, project);

  const projectsData = readJson(PROJECTS_FILE, { projects: [], activeProjectId: null });
  if (!projectsData.projects.some(p => p.id === projectId)) {
    const now = new Date().toISOString();
    projectsData.projects.push({ id: projectId, name, description: description || '', createdAt: now, updatedAt: now });
  }
  projectsData.activeProjectId = projectId;
  writeJson(PROJECTS_FILE, projectsData);

  return { projectDir, projectId, created: true };
}

function syncInventory(projectDir) {
  const projectPath = path.join(projectDir, 'project.json');
  const project = readJson(projectPath, {});
  project.inventory = {
    scenes: listJsonRel(projectDir, 'scenes'),
    characters: listJsonRel(projectDir, 'characters'),
    props: listJsonRel(projectDir, 'props')
  };
  if (!project.default_style_ref || !fs.existsSync(path.join(projectDir, project.default_style_ref))) {
    project.default_style_ref = listJsonRel(projectDir, 'styles')[0] || project.default_style_ref || 'styles/cinematic_v1.json';
  }
  writeJson(projectPath, project);
}

function preflight(projectDir, scriptPath, { force, skipSplit, skipPromote }) {
  const issues = [];
  if (!fs.existsSync(scriptPath)) issues.push(`script not found: ${scriptPath}`);

  const project = readJson(path.join(projectDir, 'project.json'), null);
  if (!project) issues.push(`project.json not found or invalid: ${path.join(projectDir, 'project.json')}`);

  for (const dir of ['scenes', 'characters', 'props']) {
    if (listJsonRel(projectDir, dir).length === 0) {
      issues.push(`${dir}/ is empty. Use --template-project or add inventory before splitting.`);
    }
  }

  if (!force) {
    if (!skipSplit && fs.existsSync(path.join(projectDir, 'shots_draft')) && fs.readdirSync(path.join(projectDir, 'shots_draft')).some(f => f.endsWith('.json'))) {
      issues.push('shots_draft/ already has drafts. Pass --force or --skip-split.');
    }
    if (!skipPromote && project?.timeline?.length) {
      issues.push('project timeline already has shots. Pass --force or --skip-promote.');
    }
  }

  return issues;
}

function runStep(name, cmd, args, cwd, results) {
  console.log(`\n▶ ${name}`);
  console.log(`  ${cmd} ${args.join(' ')}`);
  const started = Date.now();
  const run = spawnSync(cmd, args, { cwd, encoding: 'utf-8', shell: false });
  const durationMs = Date.now() - started;
  const result = {
    name,
    command: `${cmd} ${args.join(' ')}`,
    status: run.status === 0 ? 'passed' : 'failed',
    duration_ms: durationMs,
    stdout: run.stdout || '',
    stderr: run.stderr || ''
  };
  results.push(result);
  if (run.stdout) console.log(run.stdout.trim());
  if (run.stderr) console.error(run.stderr.trim());
  if (run.status !== 0) throw new Error(`${name} failed`);
}

function cleanGenerated(projectDir, { cleanDrafts, cleanShots }) {
  if (cleanDrafts) fs.rmSync(path.join(projectDir, 'shots_draft'), { recursive: true, force: true });
  if (cleanShots) {
    for (const dir of ['shots', 'prompts']) fs.rmSync(path.join(projectDir, dir), { recursive: true, force: true });
    const projectPath = path.join(projectDir, 'project.json');
    const project = readJson(projectPath, {});
    project.timeline = [];
    writeJson(projectPath, project);
  }
  ensureDir(path.join(projectDir, 'shots_draft'));
  ensureDir(path.join(projectDir, 'shots'));
  ensureDir(path.join(projectDir, 'prompts/image'));
}

function summarize(projectDir, runId, results, status, error = null) {
  const project = readJson(path.join(projectDir, 'project.json'), {});
  const timeline = project.timeline || [];
  const shots = timeline.map(item => readJson(path.join(projectDir, item.shot_file), null)).filter(Boolean);
  const imagePromptCount = fs.existsSync(path.join(projectDir, 'prompts/image'))
    ? fs.readdirSync(path.join(projectDir, 'prompts/image')).filter(f => f.endsWith('.image.json')).length
    : 0;
  const videoPromptCount = fs.existsSync(path.join(projectDir, 'prompts'))
    ? fs.readdirSync(path.join(projectDir, 'prompts')).filter(f => f.endsWith('.prompt.json')).length
    : 0;
  const longShots = shots.filter(shot => Number(shot.duration_s || 0) > 12).map(shot => shot.shot_id);
  const missingVoice = shots.filter(shot => !(shot.voiceover?.text || shot.dialogue?.text)).map(shot => shot.shot_id);
  const totalDuration = shots.reduce((sum, shot) => sum + Number(shot.duration_s || 0), 0);

  const report = {
    run_id: runId,
    status,
    error,
    project_id: project.id,
    project_dir: projectDir,
    generated_at: new Date().toISOString(),
    stop_point: 'image_prompt_ready_no_image_generation_no_tts_no_mp4',
    counts: {
      timeline_shots: timeline.length,
      shot_files: shots.length,
      image_prompt_packages: imagePromptCount,
      video_prompt_packages: videoPromptCount
    },
    total_duration_s: Math.round(totalDuration * 10) / 10,
    long_shots: longShots,
    missing_voiceover_or_dialogue: missingVoice,
    next_steps: [
      'Open the UI Preview tab and review shot order, narration, and prompt packages.',
      'Generate or upload keyframe images manually when ready.',
      'After images/takes are ready, generate TTS and compose/export only on explicit request.'
    ],
    steps: results.map(({ stdout, stderr, ...rest }) => rest)
  };

  const reportsDir = path.join(projectDir, 'reports');
  ensureDir(reportsDir);
  const jsonPath = path.join(reportsDir, `rough-cut-${runId}.json`);
  const mdPath = path.join(reportsDir, `rough-cut-${runId}.md`);
  writeJson(jsonPath, report);
  const lines = [
    `# Rough Cut Report ${runId}`,
    '',
    `Status: ${status}`,
    `Project: ${project.id || path.basename(projectDir)}`,
    `Stop point: image prompt packages ready; no image generation, no TTS, no MP4 export.`,
    '',
    `- Timeline shots: ${timeline.length}`,
    `- Total duration: ${report.total_duration_s}s`,
    `- Image prompt packages: ${imagePromptCount}`,
    `- Video prompt packages: ${videoPromptCount}`,
    `- Long shots still over 12s: ${longShots.length ? longShots.join(', ') : 'none'}`,
    `- Missing voice/dialogue: ${missingVoice.length ? missingVoice.join(', ') : 'none'}`,
    '',
    '## Next Steps',
    '',
    ...report.next_steps.map(step => `- ${step}`),
    '',
    '## Steps',
    '',
    ...report.steps.map(step => `- ${step.status}: ${step.name} (${step.duration_ms}ms)`)
  ];
  if (error) lines.splice(3, 0, `Error: ${error}`);
  fs.writeFileSync(mdPath, lines.join('\n') + '\n', 'utf-8');
  return { jsonPath, mdPath, report };
}

async function main() {
  const args = process.argv.slice(2);
  if (hasArg(args, '--help') || hasArg(args, '-h')) {
    usage();
    return;
  }

  const projectId = argValue(args, '--project-id');
  const projectDirArg = argValue(args, '--project-dir');
  const name = argValue(args, '--name');
  const description = argValue(args, '--description', '');
  const scriptArg = argValue(args, '--script', 'docs/script.txt');
  const templateProject = argValue(args, '--template-project');
  const maxDuration = Number(argValue(args, '--max-duration', '12'));
  const force = hasArg(args, '--force');
  const dryRun = hasArg(args, '--dry-run');
  const skipSplit = hasArg(args, '--skip-split');
  const skipPromote = hasArg(args, '--skip-promote');
  const runId = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);

  const projectInfo = createOrLoadProject({ projectId, projectDirArg, name, description, templateProject, force, dryRun });
  const projectDir = projectInfo.projectDir;
  const scriptPath = resolveScriptPath(scriptArg, projectDir);
  const results = [];

  console.log('🎬 Rough Cut Pipeline');
  console.log(`Project: ${projectInfo.projectId} (${projectDir})`);
  console.log(`Script: ${scriptPath}`);
  console.log('Stop point: image prompts ready. Images/TTS/MP4 are not generated.');

  if (dryRun) {
    const issues = fs.existsSync(projectDir)
      ? preflight(projectDir, scriptPath, { force, skipSplit, skipPromote })
      : [];
    console.log('\nDry run plan:');
    console.log(`- ${projectInfo.created ? 'Create' : 'Use'} project`);
    console.log(`- ${skipSplit ? 'Skip script split' : 'Split script into shots_draft'}`);
    console.log(`- ${skipPromote ? 'Skip promote' : 'Promote drafts into shots + timeline'}`);
    console.log(`- Split long shots above ${maxDuration}s`);
    console.log('- Build project context, image prompts, and video prompts');
    if (issues.length) console.log(`\nPreflight issues:\n${issues.map(issue => `- ${issue}`).join('\n')}`);
    return;
  }

  syncInventory(projectDir);
  const issues = preflight(projectDir, scriptPath, { force, skipSplit, skipPromote });
  if (issues.length) {
    issues.forEach(issue => console.error(`Preflight: ${issue}`));
    throw new Error('Preflight failed');
  }

  const stagedScriptPath = stageScript(scriptPath, projectDir);
  cleanGenerated(projectDir, { cleanDrafts: force && !skipSplit, cleanShots: force && !skipPromote });

  const commonArgs = ['--project-dir', projectDir];
  try {
    if (!skipSplit) {
      runStep('Split script into draft shots', process.execPath, ['tools/scripts/script-split.js', stagedScriptPath, ...commonArgs], ROOT, results);
    }
    if (!skipPromote) {
      runStep('Promote drafts into active shots/timeline', process.execPath, ['tools/scripts/promote-all.js', ...commonArgs], ROOT, results);
    }
    runStep('Split long shots', process.execPath, ['tools/scripts/split-long-shots.js', '--apply', '--max-duration', String(maxDuration), ...commonArgs], ROOT, results);
    runStep('Build project system prompt context', process.execPath, ['tools/scripts/build-project-context.js', ...commonArgs], ROOT, results);
    runStep('Build image prompt packages', process.execPath, ['tools/scripts/build-image-prompts.js', ...commonArgs], ROOT, results);
    runStep('Build video prompt packages', process.execPath, ['tools/scripts/build-prompts.js', ...commonArgs], ROOT, results);
    runStep('Quick structural check', process.execPath, ['tools/scripts/check-all.js', '--quick', ...commonArgs], ROOT, results);

    const { jsonPath, mdPath, report } = summarize(projectDir, runId, results, 'passed');
    console.log('\n✅ Rough cut storyboard stage is ready.');
    console.log(`Report: ${mdPath}`);
    console.log(`JSON: ${jsonPath}`);
    console.log(`Shots: ${report.counts.timeline_shots}, duration: ${report.total_duration_s}s`);
  } catch (err) {
    const { mdPath } = summarize(projectDir, runId, results, 'failed', err.message);
    console.error(`\n❌ Rough cut failed. Report: ${mdPath}`);
    process.exit(1);
  }
}

main().catch(err => {
  console.error(err.message || err);
  process.exit(1);
});
