// Auto-generated by prepare-data.ts - DO NOT EDIT
import type { ShotData, ShotSceneInput } from './types';

export interface DataManifest {
  projectName: string;
  totalShots: number;
  totalDuration: number;
  shots: ShotSceneInput[];
  generatedAt: string;
}

export const manifest: DataManifest = {
  "projectName": "红杯",
  "totalShots": 5,
  "totalDuration": 60,
  "shots": [
    {
      "shot": {
        "shot_id": "S001",
        "duration_s": 12,
        "scene_ref": "scenes/kitchen_apartment_01.json",
        "cam_setup_ref": "comic_panel_01",
        "characters": [
          {
            "ref": "characters/charA_v1.json"
          }
        ],
        "props": [
          {
            "ref": "props/mug_red_v1.json",
            "state": "story_clue"
          }
        ],
        "action": {
          "beats": [
            "午夜的雨把旧公寓包成一只黑盒。林澈回家时，厨房灯自己亮着。",
            "林澈低声说：我出门前，明明关了灯。"
          ]
        },
        "dialogue": {
          "speaker": "林澈",
          "text": "我出门前，明明关了灯。",
          "voice_id": "zh-CN-YunxiNeural"
        },
        "voiceover": {
          "speaker": "旁白",
          "text": "午夜的雨把旧公寓包成一只黑盒。林澈回家时，厨房灯自己亮着。",
          "voice_id": "zh-CN-XiaoxiaoNeural"
        },
        "continuity": {
          "state_in_ref": "states/S000_INIT.json",
          "state_changes": {
            "characters": {
              "charA_v1": {
                "location": "apartment_kitchen_or_hallway",
                "pose": "listening"
              }
            },
            "props": {
              "mug_red_v1": {
                "location": "near_main_character",
                "state": "warm_and_unexplained"
              }
            },
            "scene": {
              "lighting": "rainy night, warm lamp, cold blue shadow"
            }
          },
          "handoff_to_next": [
            "红杯仍是关键线索",
            "雨夜公寓的压迫感延续到 S002"
          ]
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "cinematic realistic suspense comic panel, stable young Chinese man identity, rainy old apartment, red mug as recurring clue, coherent low-cost storyboard frame",
          "negative": "no text artifacts, no logo, no watermark, no extra fingers, no face drift"
        }
      },
      "keyframe": "keyframe-S001.jpg",
      "audio": "audio-S001.mp3"
    },
    {
      "shot": {
        "shot_id": "S002",
        "duration_s": 12,
        "scene_ref": "scenes/kitchen_apartment_01.json",
        "cam_setup_ref": "comic_panel_02",
        "context_refs": [
          "assets/renders/S001/keyframes/frame_01.jpg"
        ],
        "characters": [
          {
            "ref": "characters/charA_v1.json"
          }
        ],
        "props": [
          {
            "ref": "props/mug_red_v1.json",
            "state": "story_clue"
          }
        ],
        "action": {
          "beats": [
            "桌上有一只红杯，杯沿还冒着热气。那不是他的杯子。",
            "林澈低声说：谁来过我家？"
          ]
        },
        "dialogue": {
          "speaker": "林澈",
          "text": "谁来过我家？",
          "voice_id": "zh-CN-YunxiNeural"
        },
        "voiceover": {
          "speaker": "旁白",
          "text": "桌上有一只红杯，杯沿还冒着热气。那不是他的杯子。",
          "voice_id": "zh-CN-XiaoxiaoNeural"
        },
        "continuity": {
          "state_in_ref": "states/S001_OUT.json",
          "state_changes": {
            "characters": {
              "charA_v1": {
                "location": "apartment_kitchen_or_hallway",
                "pose": "searching"
              }
            },
            "props": {
              "mug_red_v1": {
                "location": "near_main_character",
                "state": "warm_and_unexplained"
              }
            },
            "scene": {
              "lighting": "rainy night, warm lamp, cold blue shadow"
            }
          },
          "handoff_to_next": [
            "红杯仍是关键线索",
            "雨夜公寓的压迫感延续到 S003"
          ]
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "cinematic realistic suspense comic panel, stable young Chinese man identity, rainy old apartment, red mug as recurring clue, coherent low-cost storyboard frame",
          "negative": "no text artifacts, no logo, no watermark, no extra fingers, no face drift"
        }
      },
      "keyframe": "keyframe-S002.jpg",
      "audio": "audio-S002.mp3"
    },
    {
      "shot": {
        "shot_id": "S003",
        "duration_s": 12,
        "scene_ref": "scenes/kitchen_apartment_01.json",
        "cam_setup_ref": "comic_panel_03",
        "context_refs": [
          "assets/renders/S002/keyframes/frame_01.jpg"
        ],
        "characters": [
          {
            "ref": "characters/charA_v1.json"
          }
        ],
        "props": [
          {
            "ref": "props/mug_red_v1.json",
            "state": "story_clue"
          }
        ],
        "action": {
          "beats": [
            "手机忽然亮起，屏幕上只有一行字：别喝。",
            "林澈低声说：这是谁发的？"
          ]
        },
        "dialogue": {
          "speaker": "林澈",
          "text": "这是谁发的？",
          "voice_id": "zh-CN-YunxiNeural"
        },
        "voiceover": {
          "speaker": "旁白",
          "text": "手机忽然亮起，屏幕上只有一行字：别喝。",
          "voice_id": "zh-CN-XiaoxiaoNeural"
        },
        "continuity": {
          "state_in_ref": "states/S002_OUT.json",
          "state_changes": {
            "characters": {
              "charA_v1": {
                "location": "apartment_kitchen_or_hallway",
                "pose": "frozen"
              }
            },
            "props": {
              "mug_red_v1": {
                "location": "near_main_character",
                "state": "warm_and_unexplained"
              }
            },
            "scene": {
              "lighting": "rainy night, warm lamp, cold blue shadow"
            }
          },
          "handoff_to_next": [
            "红杯仍是关键线索",
            "雨夜公寓的压迫感延续到 S004"
          ]
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "cinematic realistic suspense comic panel, stable young Chinese man identity, rainy old apartment, red mug as recurring clue, coherent low-cost storyboard frame",
          "negative": "no text artifacts, no logo, no watermark, no extra fingers, no face drift"
        }
      },
      "keyframe": "keyframe-S003.jpg",
      "audio": "audio-S003.mp3"
    },
    {
      "shot": {
        "shot_id": "S004",
        "duration_s": 12,
        "scene_ref": "scenes/kitchen_apartment_01.json",
        "cam_setup_ref": "comic_panel_04",
        "context_refs": [
          "assets/renders/S003/keyframes/frame_01.jpg"
        ],
        "characters": [
          {
            "ref": "characters/charA_v1.json"
          }
        ],
        "props": [
          {
            "ref": "props/mug_red_v1.json",
            "state": "story_clue"
          }
        ],
        "action": {
          "beats": [
            "门外传来电梯停靠的声音，可这栋楼的电梯上周就坏了。",
            "林澈低声说：不可能。"
          ]
        },
        "dialogue": {
          "speaker": "林澈",
          "text": "不可能。",
          "voice_id": "zh-CN-YunxiNeural"
        },
        "voiceover": {
          "speaker": "旁白",
          "text": "门外传来电梯停靠的声音，可这栋楼的电梯上周就坏了。",
          "voice_id": "zh-CN-XiaoxiaoNeural"
        },
        "continuity": {
          "state_in_ref": "states/S003_OUT.json",
          "state_changes": {
            "characters": {
              "charA_v1": {
                "location": "apartment_kitchen_or_hallway",
                "pose": "listening"
              }
            },
            "props": {
              "mug_red_v1": {
                "location": "near_main_character",
                "state": "warm_and_unexplained"
              }
            },
            "scene": {
              "lighting": "rainy night, warm lamp, cold blue shadow"
            }
          },
          "handoff_to_next": [
            "红杯仍是关键线索",
            "雨夜公寓的压迫感延续到 S005"
          ]
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "cinematic realistic suspense comic panel, stable young Chinese man identity, rainy old apartment, red mug as recurring clue, coherent low-cost storyboard frame",
          "negative": "no text artifacts, no logo, no watermark, no extra fingers, no face drift"
        }
      },
      "keyframe": "keyframe-S004.jpg",
      "audio": "audio-S004.mp3"
    },
    {
      "shot": {
        "shot_id": "S005",
        "duration_s": 12,
        "scene_ref": "scenes/kitchen_apartment_01.json",
        "cam_setup_ref": "comic_panel_05",
        "context_refs": [
          "assets/renders/S004/keyframes/frame_01.jpg"
        ],
        "characters": [
          {
            "ref": "characters/charA_v1.json"
          }
        ],
        "props": [
          {
            "ref": "props/mug_red_v1.json",
            "state": "story_clue"
          }
        ],
        "action": {
          "beats": [
            "他走到猫眼前，走廊空着，灯却一盏一盏熄灭。",
            "林澈低声说：有人在外面。"
          ]
        },
        "dialogue": {
          "speaker": "林澈",
          "text": "有人在外面。",
          "voice_id": "zh-CN-YunxiNeural"
        },
        "voiceover": {
          "speaker": "旁白",
          "text": "他走到猫眼前，走廊空着，灯却一盏一盏熄灭。",
          "voice_id": "zh-CN-XiaoxiaoNeural"
        },
        "continuity": {
          "state_in_ref": "states/S004_OUT.json",
          "state_changes": {
            "characters": {
              "charA_v1": {
                "location": "apartment_kitchen_or_hallway",
                "pose": "searching"
              }
            },
            "props": {
              "mug_red_v1": {
                "location": "near_main_character",
                "state": "warm_and_unexplained"
              }
            },
            "scene": {
              "lighting": "rainy night, warm lamp, cold blue shadow"
            }
          },
          "handoff_to_next": [
            "红杯仍是关键线索",
            "雨夜公寓的压迫感延续到 S006"
          ]
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "cinematic realistic suspense comic panel, stable young Chinese man identity, rainy old apartment, red mug as recurring clue, coherent low-cost storyboard frame",
          "negative": "no text artifacts, no logo, no watermark, no extra fingers, no face drift"
        }
      },
      "keyframe": "keyframe-S005.jpg",
      "audio": "audio-S005.mp3"
    }
  ],
  "generatedAt": "2026-05-25T05:13:22.762Z"
};
