// Auto-generated by prepare-data.mjs - DO NOT EDIT
import type { ShotData, ShotSceneInput } from './types';

export interface DataManifest {
  projectName: string;
  totalShots: number;
  totalDuration: number;
  shots: ShotSceneInput[];
  generatedAt: string;
}

export const manifest: DataManifest = {
  "projectName": "滤芯洁净车间",
  "totalShots": 9,
  "totalDuration": 70,
  "shots": [
    {
      "shot": {
        "shot_id": "S001",
        "duration_s": 8,
        "scene_ref": "scenes/scene_entrance.json",
        "cam_setup_ref": "comic_panel_01",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/warning_signage.json",
            "state": "displayed"
          }
        ],
        "action": {
          "beats": [
            "Visitors gather at clean room entrance, reading signage and access control panel"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "欢迎参观滤芯洁净车间。本车间为洁净管控区域，进入前请先了解以下注意事项。为了保证产品质量、现场安全和洁净环境，请大家按照要求进入，不随意、不触碰、不拍摄。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 cinematic wide shot, clean room entrance with door access panel and warning signage, group of visitors in casual clothes standing and reading, bright industrial lighting, eye-level angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, dark lighting, cluttered background"
        },
        "context_refs": []
      },
      "keyframe": "keyframe-S001.png",
      "audio": "audio-S001.mp3"
    },
    {
      "shot": {
        "shot_id": "S002",
        "duration_s": 6,
        "scene_ref": "scenes/scene_entrance.json",
        "cam_setup_ref": "comic_panel_02",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/warning_signage.json",
            "state": "displayed"
          }
        ],
        "action": {
          "beats": [
            "Visitor pauses at entrance, reading notice board with health and item restrictions"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "进入车间前，请确认自身状态。如有明显感冒、咳嗽、发热，或身上有明显异味、粉尘、油污等情况，不建议进入洁净区域。随身物品请按要求存放，食品、饮料、纸箱、普通纸张等易产尘物品不得带入车间。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 medium shot, visitor reading notice board at clean room entrance, notice board with health guidelines and prohibited items list, bright overhead lighting, slightly low angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S001/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": "keyframe-S002.png",
      "audio": "audio-S002.mp3"
    },
    {
      "shot": {
        "shot_id": "S003",
        "duration_s": 10,
        "scene_ref": "scenes/scene_changing.json",
        "cam_setup_ref": "comic_panel_01",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/running_equipment.json",
            "state": "inactive"
          },
          {
            "ref": "props/recycle_bin.json",
            "state": "empty"
          }
        ],
        "action": {
          "beats": [
            "Visitors in changing area, sequentially putting on clean cap, mask, clean suit, and shoe covers"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "进入洁净车间必须按要求更衣。请依次穿戴洁净帽、口罩、洁净服、洁净鞋或鞋套。头发必须完全包入帽内，口罩遮住口鼻，洁净服拉链扣好，不得敞开。穿戴完成后，检查衣袖、裤脚、帽口是否整理到位。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 cinematic wide shot, clean room changing area with lockers and benches, visitors in process of donning clean suits, caps, masks, and shoe covers, bright white lighting, eye-level angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, missing safety equipment, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S002/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": "keyframe-S003.png",
      "audio": "audio-S003.mp3"
    },
    {
      "shot": {
        "shot_id": "S004",
        "duration_s": 8,
        "scene_ref": "scenes/scene_air_shower.json",
        "cam_setup_ref": "comic_panel_02",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/no_photography_sign.json",
            "state": "displayed"
          }
        ],
        "action": {
          "beats": [
            "Visitor enters air shower chamber, raises arms, slowly rotates as air jets blow"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "更衣完成后，请按要求进入风淋室。风淋过程中，人员应缓慢转身，让气流充分吹扫衣物表面。风淋未结束前，不得强行开门或提前离开。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 medium shot, interior of air shower chamber with air nozzles on walls, visitor in clean suit raising arms and slowly turning, bright blue-tinted lighting, eye-level angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S003/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": "keyframe-S004.png",
      "audio": "audio-S004.mp3"
    },
    {
      "shot": {
        "shot_id": "S005",
        "duration_s": 10,
        "scene_ref": "scenes/scene_interior.json",
        "cam_setup_ref": "comic_panel_01",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/running_equipment.json",
            "state": "active"
          },
          {
            "ref": "props/warning_signage.json",
            "state": "displayed"
          }
        ],
        "action": {
          "beats": [
            "Visitors walk along designated pathway in clean room, staying away from machinery and yellow warning lines"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "进入车间后，请按指定路线参观。参观过程中，不得脱帽、摘口罩，不得随意触摸设备、物料、工装、产品和记录表单。未经允许，不得操作设备，不得进入黄线以内或设备防护区域。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 cinematic wide shot, clean room interior with running machinery and yellow warning lines on floor, group of visitors in clean suits walking along designated path, bright industrial overhead lighting, eye-level angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, missing safety equipment, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S004/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": "keyframe-S005.png",
      "audio": "audio-S005.mp3"
    },
    {
      "shot": {
        "shot_id": "S006",
        "duration_s": 6,
        "scene_ref": "scenes/scene_interior.json",
        "cam_setup_ref": "comic_panel_02",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/no_photography_sign.json",
            "state": "displayed"
          }
        ],
        "action": {
          "beats": [
            "A no photography sign is prominently displayed on the wall",
            "A group of visitors stands in a designated listening area, attentively facing the sign"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "车间内涉及工艺、设备和产品信息。未经许可，不得拍照、录像或直播。如需交流问题，请在指定区域进行，不要影响现场人员操作。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 medium shot, clean room interior with a no photography sign on the wall, a group of visitors in white clean suits standing in a designated area listening, bright industrial overhead lighting, eye-level angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, missing safety equipment, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S005/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": null,
      "audio": null
    },
    {
      "shot": {
        "shot_id": "S007",
        "duration_s": 8,
        "scene_ref": "scenes/scene_interior.json",
        "cam_setup_ref": "comic_panel_01",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/running_equipment.json",
            "state": "operating"
          },
          {
            "ref": "props/warning_signage.json",
            "state": "visible"
          }
        ],
        "action": {
          "beats": [
            "Wide view of the clean room interior showing running machinery and pipes",
            "Warning signs are visible on equipment and along pathways",
            "Visitors walk carefully on marked floor paths"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "车间内存在运行设备、管道、气路、水路和电气装置。请不要靠近旋转部件、加热部件和压力管路。不要倚靠设备，不要触碰阀门、按钮、线缆和管道。行走时注意地面，防止滑倒、绊倒和碰撞。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 wide establishing shot, clean room interior with running machinery, pipes, and warning signage, visitors walking on marked floor paths, bright industrial overhead lighting, high angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, missing safety equipment, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S006/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": null,
      "audio": null
    },
    {
      "shot": {
        "shot_id": "S008",
        "duration_s": 6,
        "scene_ref": "scenes/scene_exit.json",
        "cam_setup_ref": "comic_panel_02",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/recycle_bin.json",
            "state": "available"
          },
          {
            "ref": "props/running_equipment.json",
            "state": "idle"
          }
        ],
        "action": {
          "beats": [
            "Visitors follow a designated exit route",
            "They place clean suits, shoe covers, and masks into a recycle bin"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "参观结束后，请按指定路线离开洁净车间。洁净服、鞋套、口罩等按现场要求回收或放置，不得随意丢弃。离开后如有意见或问题，可统一反馈给陪同人员。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 medium shot, clean room exit area with visitors removing and placing clean suits into a recycle bin, bright industrial overhead lighting, eye-level angle, photorealistic, highly detailed, 8K, industrial documentary style",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, missing safety equipment, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S007/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": null,
      "audio": null
    },
    {
      "shot": {
        "shot_id": "S009",
        "duration_s": 8,
        "scene_ref": "scenes/scene_interior.json",
        "cam_setup_ref": "comic_panel_01",
        "characters": [
          {
            "ref": "characters/visitor_group.json"
          }
        ],
        "props": [
          {
            "ref": "props/running_equipment.json",
            "state": "operating"
          },
          {
            "ref": "props/warning_signage.json",
            "state": "visible"
          }
        ],
        "action": {
          "beats": [
            "Wide shot of the entire clean room with all equipment running",
            "Key safety tips overlay on the screen"
          ]
        },
        "dialogue": null,
        "voiceover": {
          "speaker": "Narrator",
          "text": "洁净车间管理的核心，是减少污染、保证质量、确保安全。请大家做到：规范更衣、完成风淋、只看不摸、不越线、不拍摄。感谢配合。",
          "voice_id": "narrator_male_01"
        },
        "budget": {
          "tier": "cheap",
          "max_regen": 1
        },
        "prompt": {
          "positive": "16:9 wide establishing shot, clean room interior with all machinery running and warning signs visible, visitors standing in a group, bright industrial overhead lighting, high angle, photorealistic, highly detailed, 8K, industrial documentary style, text overlay with safety tips",
          "negative": "blurry, low quality, distorted faces, wrong proportions, text artifacts, watermark, logo, extra limbs, missing safety equipment, dark lighting, cluttered background"
        },
        "context_refs": [
          "assets/renders/S008/keyframes/frame_01.jpg"
        ]
      },
      "keyframe": null,
      "audio": null
    }
  ],
  "generatedAt": "2026-05-25T14:59:10.466Z"
};
