import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '../../');
const PUBLIC_DIR = path.resolve(__dirname, '../public');

interface ShotData {
  shot_id: string;
  duration_s: number;
  cam_setup_ref?: string;
  action?: { beats?: string[] };
  dialogue?: { speaker: string; text: string; voice_id?: string };
  voiceover?: { speaker?: string; text: string; voice_id?: string };
  scene_ref?: string;
}

interface ShotSceneInput {
  shot: ShotData;
  keyframe: string | null;
  audio: string | null;
}

interface DataManifest {
  projectName: string;
  totalShots: number;
  totalDuration: number;
  shots: ShotSceneInput[];
  generatedAt: string;
}

function readJson<T>(rel: string): T | null {
  try {
    return JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf-8')) as T;
  } catch {
    return null;
  }
}

function findKeyframe(shotId: string): string | null {
  const keyframeDir = path.join(ROOT, 'assets/renders', shotId, 'keyframes');
  if (!fs.existsSync(keyframeDir)) return null;

  const imageExts = ['.jpg', '.jpeg', '.png', '.webp'];
  for (const ext of imageExts) {
    const file = path.join(keyframeDir, `frame_01${ext}`);
    if (fs.existsSync(file)) {
      // Return path relative to render/public for Remotion staticFile()
      const destName = `keyframe-${shotId}${ext}`;
      const destPath = path.join(PUBLIC_DIR, destName);
      fs.copyFileSync(file, destPath);
      return destName;
    }
  }
  return null;
}

function findAudio(shotId: string): string | null {
  const audioPath = path.join(ROOT, 'assets/audio', `${shotId}.mp3`);
  if (fs.existsSync(audioPath)) {
    const destName = `audio-${shotId}.mp3`;
    const destPath = path.join(PUBLIC_DIR, destName);
    fs.copyFileSync(audioPath, destPath);
    return destName;
  }
  return null;
}

function main() {
  const project = readJson<{ name: string; timeline: { shot_id: string }[] }>('project.json');
  if (!project) {
    console.error('project.json not found');
    process.exit(1);
  }

  fs.mkdirSync(PUBLIC_DIR, { recursive: true });

  const shots: ShotSceneInput[] = [];
  let totalDuration = 0;

  for (const entry of project.timeline || []) {
    const shot = readJson<ShotData>(`shots/${entry.shot_id}.json`);
    if (!shot) {
      console.warn(`Shot ${entry.shot_id} not found, skipping`);
      continue;
    }

    const keyframe = findKeyframe(shot.shot_id);
    const audio = findAudio(shot.shot_id);

    shots.push({ shot, keyframe, audio });
    totalDuration += shot.duration_s;

    const kfStatus = keyframe ? `✓` : `✗`;
    const audioStatus = audio ? `✓` : `✗`;
    console.log(`  ${shot.shot_id} keyframe:${kfStatus} audio:${audioStatus} (${shot.duration_s}s)`);
  }

  const manifest: DataManifest = {
    projectName: project.name || 'AI Film Studio',
    totalShots: shots.length,
    totalDuration,
    shots,
    generatedAt: new Date().toISOString()
  };

  fs.writeFileSync(
    path.join(PUBLIC_DIR, 'data.json'),
    JSON.stringify(manifest, null, 2)
  );

  // Generate importable TypeScript module for Remotion
  const tsModule = `// Auto-generated by prepare-data.ts - DO NOT EDIT
import type { ShotData, ShotSceneInput } from './types';

export interface DataManifest {
  projectName: string;
  totalShots: number;
  totalDuration: number;
  shots: ShotSceneInput[];
  generatedAt: string;
}

export const manifest: DataManifest = ${JSON.stringify(manifest, null, 2)};
`;
  fs.writeFileSync(path.join(path.dirname(PUBLIC_DIR), 'src', 'manifest.ts'), tsModule);

  console.log(`\nPrepared ${shots.length} shots (${totalDuration}s total)`);
  console.log('Generated: render/src/manifest.ts + render/public/data.json');
  console.log('Assets copied to render/public/');
}

main();
