import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from '../../tools/scripts/shared/dirs.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const RENDER_ROOT = path.resolve(__dirname, '..');
const PUBLIC_DIR = path.join(RENDER_ROOT, 'public');
const SRC_DIR = path.join(RENDER_ROOT, 'src');
const { workDir: WORK_DIR } = parseArgs();

function readJson(relPath) {
  try {
    return JSON.parse(fs.readFileSync(path.join(WORK_DIR, relPath), 'utf-8'));
  } catch {
    return null;
  }
}

function copyIfExists(sourcePath, destName) {
  if (!fs.existsSync(sourcePath)) return null;
  fs.copyFileSync(sourcePath, path.join(PUBLIC_DIR, destName));
  return destName;
}

function findKeyframe(shotId) {
  const keyframeDir = path.join(WORK_DIR, 'assets/renders', shotId, 'keyframes');
  if (!fs.existsSync(keyframeDir)) return null;

  for (const ext of ['.jpg', '.jpeg', '.png', '.webp']) {
    const copiedName = copyIfExists(
      path.join(keyframeDir, `frame_01${ext}`),
      `keyframe-${shotId}${ext}`
    );
    if (copiedName) return copiedName;
  }

  return null;
}

function findAudio(shotId) {
  return copyIfExists(
    path.join(WORK_DIR, 'assets/audio', `${shotId}.mp3`),
    `audio-${shotId}.mp3`
  );
}

function main() {
  const project = readJson('project.json');
  if (!project) {
    console.error(`project.json not found in ${WORK_DIR}`);
    process.exit(1);
  }

  fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  fs.mkdirSync(SRC_DIR, { recursive: true });

  const shots = [];
  let totalDuration = 0;

  for (const entry of project.timeline || []) {
    const shot = readJson(`shots/${entry.shot_id}.json`);
    if (!shot) {
      console.warn(`Shot ${entry.shot_id} not found, skipping`);
      continue;
    }

    const keyframe = findKeyframe(shot.shot_id);
    const audio = findAudio(shot.shot_id);

    shots.push({ shot, keyframe, audio });
    totalDuration += shot.duration_s;

    const kfStatus = keyframe ? 'ok' : 'missing';
    const audioStatus = audio ? 'ok' : 'missing';
    console.log(`  ${shot.shot_id} keyframe:${kfStatus} audio:${audioStatus} (${shot.duration_s}s)`);
  }

  const manifest = {
    projectName: project.name || 'AI Film Studio',
    totalShots: shots.length,
    totalDuration,
    shots,
    generatedAt: new Date().toISOString()
  };

  fs.writeFileSync(
    path.join(PUBLIC_DIR, 'data.json'),
    JSON.stringify(manifest, null, 2)
  );

  const tsModule = `// Auto-generated by prepare-data.mjs - DO NOT EDIT
import type { ShotData, ShotSceneInput } from './types';

export interface DataManifest {
  projectName: string;
  totalShots: number;
  totalDuration: number;
  shots: ShotSceneInput[];
  generatedAt: string;
}

export const manifest: DataManifest = ${JSON.stringify(manifest, null, 2)};
`;

  fs.writeFileSync(path.join(SRC_DIR, 'manifest.ts'), tsModule);

  console.log(`\nPrepared ${shots.length} shots (${totalDuration}s total) from ${WORK_DIR}`);
  console.log('Generated: render/src/manifest.ts + render/public/data.json');
  console.log('Assets copied to render/public/');
}

main();
